# TCL File Generated by Component Editor 18.1
# Fri May 06 12:48:53 CDT 2022
# DO NOT MODIFY


# 
# Audio_Synthesizer_Module "Audio Synthesizer Module" v1.0
# Dan Piper 2022.05.06.12:48:53
# Generates audio samples from velocity and note input from NIOS II. Allows for selection of ADSR length and magnitude.
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module Audio_Synthesizer_Module
# 
set_module_property DESCRIPTION "Generates audio samples from velocity and note input from NIOS II. Allows for selection of ADSR length and magnitude."
set_module_property NAME Audio_Synthesizer_Module
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Personal IP"
set_module_property AUTHOR "Dan Piper"
set_module_property DISPLAY_NAME "Audio Synthesizer Module"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL synth_ip
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file synth_ip.sv SYSTEM_VERILOG PATH synth_ip.sv TOP_LEVEL_FILE
add_fileset_file datapath.sv SYSTEM_VERILOG PATH datapath.sv
add_fileset_file f_table.sv SYSTEM_VERILOG PATH f_table.sv
add_fileset_file wavetable.sv SYSTEM_VERILOG PATH wavetable.sv


# 
# parameters
# 


# 
# display items
# 


# 
# connection point CLK
# 
add_interface CLK clock end
set_interface_property CLK clockRate 100000000
set_interface_property CLK ENABLED true
set_interface_property CLK EXPORT_OF ""
set_interface_property CLK PORT_NAME_MAP ""
set_interface_property CLK CMSIS_SVD_VARIABLES ""
set_interface_property CLK SVD_ADDRESS_GROUP ""

add_interface_port CLK CLK clk Input 1


# 
# connection point RESET
# 
add_interface RESET reset end
set_interface_property RESET associatedClock CLK
set_interface_property RESET synchronousEdges DEASSERT
set_interface_property RESET ENABLED true
set_interface_property RESET EXPORT_OF ""
set_interface_property RESET PORT_NAME_MAP ""
set_interface_property RESET CMSIS_SVD_VARIABLES ""
set_interface_property RESET SVD_ADDRESS_GROUP ""

add_interface_port RESET RESET reset Input 1


# 
# connection point avalon_slave
# 
add_interface avalon_slave avalon end
set_interface_property avalon_slave addressUnits WORDS
set_interface_property avalon_slave associatedClock CLK
set_interface_property avalon_slave associatedReset RESET
set_interface_property avalon_slave bitsPerSymbol 8
set_interface_property avalon_slave burstOnBurstBoundariesOnly false
set_interface_property avalon_slave burstcountUnits WORDS
set_interface_property avalon_slave explicitAddressSpan 0
set_interface_property avalon_slave holdTime 0
set_interface_property avalon_slave linewrapBursts false
set_interface_property avalon_slave maximumPendingReadTransactions 0
set_interface_property avalon_slave maximumPendingWriteTransactions 0
set_interface_property avalon_slave readLatency 0
set_interface_property avalon_slave readWaitTime 1
set_interface_property avalon_slave setupTime 0
set_interface_property avalon_slave timingUnits Cycles
set_interface_property avalon_slave writeWaitTime 0
set_interface_property avalon_slave ENABLED true
set_interface_property avalon_slave EXPORT_OF ""
set_interface_property avalon_slave PORT_NAME_MAP ""
set_interface_property avalon_slave CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave AVL_ADDR address Input 8
add_interface_port avalon_slave AVL_READ read Input 1
add_interface_port avalon_slave AVL_READDATA readdata Output 32
add_interface_port avalon_slave AVL_WRITE write Input 1
add_interface_port avalon_slave AVL_WRITEDATA writedata Input 32
set_interface_assignment avalon_slave embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave embeddedsw.configuration.isPrintableDevice 0


# 
# connection point INPUTS
# 
add_interface INPUTS conduit end
set_interface_property INPUTS associatedClock CLK
set_interface_property INPUTS associatedReset ""
set_interface_property INPUTS ENABLED true
set_interface_property INPUTS EXPORT_OF ""
set_interface_property INPUTS PORT_NAME_MAP ""
set_interface_property INPUTS CMSIS_SVD_VARIABLES ""
set_interface_property INPUTS SVD_ADDRESS_GROUP ""

add_interface_port INPUTS RUN run Input 1
add_interface_port INPUTS FIFO_FULL fifo_full Input 1


# 
# connection point OUTPUTS
# 
add_interface OUTPUTS conduit end
set_interface_property OUTPUTS associatedClock CLK
set_interface_property OUTPUTS associatedReset ""
set_interface_property OUTPUTS ENABLED true
set_interface_property OUTPUTS EXPORT_OF ""
set_interface_property OUTPUTS PORT_NAME_MAP ""
set_interface_property OUTPUTS CMSIS_SVD_VARIABLES ""
set_interface_property OUTPUTS SVD_ADDRESS_GROUP ""

add_interface_port OUTPUTS LD_FIFO ld_fifo Output 1
add_interface_port OUTPUTS TONE tone Output 32

