transcript on
if {[file exists rtl_work]} {
	vdel -lib rtl_work -all
}
vlib rtl_work
vmap work rtl_work

vlib Audio_Synthesizer_SoC
vmap Audio_Synthesizer_SoC Audio_Synthesizer_SoC
vlog -vlog01compat -work Audio_Synthesizer_SoC +incdir+C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis {C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/Audio_Synthesizer_SoC.v}
vlog -vlog01compat -work Audio_Synthesizer_SoC +incdir+C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules {C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules/altera_reset_controller.v}
vlog -vlog01compat -work Audio_Synthesizer_SoC +incdir+C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules {C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules/altera_reset_synchronizer.v}
vlog -vlog01compat -work Audio_Synthesizer_SoC +incdir+C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules {C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules/Audio_Synthesizer_SoC_mm_interconnect_0.v}
vlog -vlog01compat -work Audio_Synthesizer_SoC +incdir+C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules {C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules/Audio_Synthesizer_SoC_mm_interconnect_0_avalon_st_adapter_005.v}
vlog -vlog01compat -work Audio_Synthesizer_SoC +incdir+C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules {C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules/Audio_Synthesizer_SoC_mm_interconnect_0_avalon_st_adapter.v}
vlog -vlog01compat -work Audio_Synthesizer_SoC +incdir+C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules {C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules/altera_avalon_sc_fifo.v}
vlog -vlog01compat -work Audio_Synthesizer_SoC +incdir+C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules {C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules/Audio_Synthesizer_SoC_usb_rst.v}
vlog -vlog01compat -work Audio_Synthesizer_SoC +incdir+C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules {C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules/Audio_Synthesizer_SoC_usb_gpx.v}
vlog -vlog01compat -work Audio_Synthesizer_SoC +incdir+C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules {C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules/Audio_Synthesizer_SoC_timer_0.v}
vlog -vlog01compat -work Audio_Synthesizer_SoC +incdir+C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules {C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules/Audio_Synthesizer_SoC_sysid_qsys_0.v}
vlog -vlog01compat -work Audio_Synthesizer_SoC +incdir+C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules {C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules/Audio_Synthesizer_SoC_spi_0.v}
vlog -vlog01compat -work Audio_Synthesizer_SoC +incdir+C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules {C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules/Audio_Synthesizer_SoC_pll_0.v}
vlog -vlog01compat -work Audio_Synthesizer_SoC +incdir+C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules {C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules/Audio_Synthesizer_SoC_onchip_memory2_0.v}
vlog -vlog01compat -work Audio_Synthesizer_SoC +incdir+C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules {C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules/Audio_Synthesizer_SoC_nios2_gen2_0.v}
vlog -vlog01compat -work Audio_Synthesizer_SoC +incdir+C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules {C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules/Audio_Synthesizer_SoC_nios2_gen2_0_cpu.v}
vlog -vlog01compat -work Audio_Synthesizer_SoC +incdir+C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules {C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules/Audio_Synthesizer_SoC_nios2_gen2_0_cpu_debug_slave_sysclk.v}
vlog -vlog01compat -work Audio_Synthesizer_SoC +incdir+C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules {C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules/Audio_Synthesizer_SoC_nios2_gen2_0_cpu_debug_slave_tck.v}
vlog -vlog01compat -work Audio_Synthesizer_SoC +incdir+C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules {C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules/Audio_Synthesizer_SoC_nios2_gen2_0_cpu_debug_slave_wrapper.v}
vlog -vlog01compat -work Audio_Synthesizer_SoC +incdir+C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules {C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules/Audio_Synthesizer_SoC_nios2_gen2_0_cpu_test_bench.v}
vlog -vlog01compat -work Audio_Synthesizer_SoC +incdir+C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules {C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules/Audio_Synthesizer_SoC_leds_pio.v}
vlog -vlog01compat -work Audio_Synthesizer_SoC +incdir+C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules {C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules/Audio_Synthesizer_SoC_jtag_uart_0.v}
vlog -vlog01compat -work Audio_Synthesizer_SoC +incdir+C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules {C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules/altera_avalon_i2c.v}
vlog -vlog01compat -work Audio_Synthesizer_SoC +incdir+C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules {C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules/altera_avalon_i2c_csr.v}
vlog -vlog01compat -work Audio_Synthesizer_SoC +incdir+C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules {C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules/altera_avalon_i2c_clk_cnt.v}
vlog -vlog01compat -work Audio_Synthesizer_SoC +incdir+C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules {C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules/altera_avalon_i2c_condt_det.v}
vlog -vlog01compat -work Audio_Synthesizer_SoC +incdir+C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules {C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules/altera_avalon_i2c_condt_gen.v}
vlog -vlog01compat -work Audio_Synthesizer_SoC +incdir+C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules {C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules/altera_avalon_i2c_fifo.v}
vlog -vlog01compat -work Audio_Synthesizer_SoC +incdir+C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules {C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules/altera_avalon_i2c_mstfsm.v}
vlog -vlog01compat -work Audio_Synthesizer_SoC +incdir+C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules {C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules/altera_avalon_i2c_rxshifter.v}
vlog -vlog01compat -work Audio_Synthesizer_SoC +incdir+C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules {C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules/altera_avalon_i2c_txshifter.v}
vlog -vlog01compat -work Audio_Synthesizer_SoC +incdir+C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules {C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules/altera_avalon_i2c_spksupp.v}
vlog -vlog01compat -work Audio_Synthesizer_SoC +incdir+C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules {C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules/altera_avalon_i2c_txout.v}
vlog -vlog01compat -work Audio_Synthesizer_SoC +incdir+C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules {C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules/Audio_Synthesizer_SoC_hex_digits_pio.v}
vlog -vlog01compat -work work +incdir+C:/Users/dpipe/OneDrive/Audio_Synthesizer {C:/Users/dpipe/OneDrive/Audio_Synthesizer/FIFO.v}
vlog -sv -work Audio_Synthesizer_SoC +incdir+C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules {C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules/Audio_Synthesizer_SoC_irq_mapper.sv}
vlog -sv -work Audio_Synthesizer_SoC +incdir+C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules {C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules/Audio_Synthesizer_SoC_mm_interconnect_0_avalon_st_adapter_005_error_adapter_0.sv}
vlog -sv -work Audio_Synthesizer_SoC +incdir+C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules {C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules/Audio_Synthesizer_SoC_mm_interconnect_0_avalon_st_adapter_error_adapter_0.sv}
vlog -sv -work Audio_Synthesizer_SoC +incdir+C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules {C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules/altera_merlin_width_adapter.sv}
vlog -sv -work Audio_Synthesizer_SoC +incdir+C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules {C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules/altera_merlin_burst_uncompressor.sv}
vlog -sv -work Audio_Synthesizer_SoC +incdir+C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules {C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules/Audio_Synthesizer_SoC_mm_interconnect_0_rsp_mux.sv}
vlog -sv -work Audio_Synthesizer_SoC +incdir+C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules {C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules/altera_merlin_arbitrator.sv}
vlog -sv -work Audio_Synthesizer_SoC +incdir+C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules {C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules/Audio_Synthesizer_SoC_mm_interconnect_0_rsp_demux.sv}
vlog -sv -work Audio_Synthesizer_SoC +incdir+C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules {C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules/Audio_Synthesizer_SoC_mm_interconnect_0_cmd_mux.sv}
vlog -sv -work Audio_Synthesizer_SoC +incdir+C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules {C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules/Audio_Synthesizer_SoC_mm_interconnect_0_cmd_demux.sv}
vlog -sv -work Audio_Synthesizer_SoC +incdir+C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules {C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules/altera_merlin_burst_adapter.sv}
vlog -sv -work Audio_Synthesizer_SoC +incdir+C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules {C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules/altera_merlin_burst_adapter_uncmpr.sv}
vlog -sv -work Audio_Synthesizer_SoC +incdir+C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules {C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules/Audio_Synthesizer_SoC_mm_interconnect_0_router_007.sv}
vlog -sv -work Audio_Synthesizer_SoC +incdir+C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules {C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules/Audio_Synthesizer_SoC_mm_interconnect_0_router_002.sv}
vlog -sv -work Audio_Synthesizer_SoC +incdir+C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules {C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules/Audio_Synthesizer_SoC_mm_interconnect_0_router.sv}
vlog -sv -work Audio_Synthesizer_SoC +incdir+C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules {C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules/altera_merlin_slave_agent.sv}
vlog -sv -work Audio_Synthesizer_SoC +incdir+C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules {C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules/altera_merlin_master_agent.sv}
vlog -sv -work Audio_Synthesizer_SoC +incdir+C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules {C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules/altera_merlin_slave_translator.sv}
vlog -sv -work Audio_Synthesizer_SoC +incdir+C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules {C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules/altera_merlin_master_translator.sv}
vlog -sv -work Audio_Synthesizer_SoC +incdir+C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules {C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules/test_wave_table.sv}
vlog -sv -work Audio_Synthesizer_SoC +incdir+C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules {C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules/lin_interp_64.sv}
vlog -sv -work Audio_Synthesizer_SoC +incdir+C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules {C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules/f_table.sv}
vlog -sv -work work +incdir+C:/Users/dpipe/OneDrive/Audio_Synthesizer {C:/Users/dpipe/OneDrive/Audio_Synthesizer/TOP.sv}
vlog -sv -work work +incdir+C:/Users/dpipe/OneDrive/Audio_Synthesizer {C:/Users/dpipe/OneDrive/Audio_Synthesizer/HexDriver.sv}
vlog -sv -work work +incdir+C:/Users/dpipe/OneDrive/Audio_Synthesizer {C:/Users/dpipe/OneDrive/Audio_Synthesizer/I2S.sv}
vlog -sv -work Audio_Synthesizer_SoC +incdir+C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules {C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules/synth_ip.sv}
vlog -sv -work Audio_Synthesizer_SoC +incdir+C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules {C:/Users/dpipe/OneDrive/Audio_Synthesizer/Audio_Synthesizer_SoC/synthesis/submodules/datapath.sv}

vlog -sv -work work +incdir+C:/Users/dpipe/OneDrive/Audio_Synthesizer {C:/Users/dpipe/OneDrive/Audio_Synthesizer/testbench.sv}

vsim -t 1ps -L altera_ver -L lpm_ver -L sgate_ver -L altera_mf_ver -L altera_lnsim_ver -L cyclonev_ver -L cyclonev_hssi_ver -L cyclonev_pcie_hip_ver -L rtl_work -L work -L Audio_Synthesizer_SoC -voptargs="+acc"  testbench

add wave *
view structure
view signals
run 1 sec
